### ISSUE TITLE
Make repo PEP8 compliant

### ISSUE THREAD

**Issue by amitabhnag** [amitabhnag/FakeReviewGenerator#10]

**Comment by amitabhnag** [comment]
Amitabh:
scripts/
	beam.py 
	eval.py 
	model.py 
	sample.py 
	train.py 

Toan:
scripts/
	translate.py 
	utils.py 
scripts/tests/
	test_*.py
setup.py

**Comment by amitabhnag** [comment]
pylint <*.py>

**Comment by amitabhnag** [comment]
Status update:
Done:
sample.py
train.py
eval.py 
In progress:
beam.py
model.py

**Comment by amitabhnag** [comment]
Add attribution to the files that we borrowed

**Comment by lmtoan** [comment]
My own checklist:
- [x] utils.py
- [x] tests/test_utils.py
- [x] tests/test_beam.py
- [x] tests/test_train.py
- [x] tests/test_eval.py
- [x] translate.py
- [x] tests/test_translate.py
- [ ] setup.py

**Comment by amitabhnag** [comment]
completed beam.py and model.py. closing task
