### ISSUE TITLE
Documentation changes

### ISSUE THREAD

**Issue by amitabhnag** [amitabhnag/FakeReviewGenerator#25]
1) Readme.md - Add info about the demo script in readme.md [Gautam]
2) Add directory structure [Toan]
3) Add Amazon dataset and Pitchfork details of the datasets - Kaggle links,  - Gautam/Amitabh
4) DesignDoc - Diagram needs to be updated - remove ipython and add google translate and the grammar check - Amitabh

**Comment by amitabhnag** [comment]
#4 is done. Design doc is updated

**Comment by amitabhnag** [comment]
#3 is done from Amitabh side

**Comment by lmtoan** [comment]
#2 is done. Checkout the Readme.md

**Comment by Gmoog** [comment]
#1 and #3 are done. Guess we can close this.
