### ISSUE TITLE
Clean Up Amazon Review Dataset

### ISSUE THREAD

**Issue by lmtoan** [amitabhnag/FakeReviewGenerator#5]
Follow this link https://www.kaggle.com/bittlingmayer/amazonreviews. Convert to `.txt` file to experiment with the generation pipeline.

**Comment by amitabhnag** [comment]
Added Amazon food reviews from https://www.kaggle.com/snap/amazon-fine-food-reviews/data. File availlable under: FakeReviewGenerator\working. Here are the files:

AmazonFood_Reviews.csv.zip - data downloaded from Kaggle
AmazonFood_Reviews_FullText_Raw.csv - All raw text
AmazonFood_Reviews_ReducedText_Raw_1.csv - reduced data set
AmazonFood_Reviews_ReducedText_Clean_1.txt - reduced clean dataset. **USE THIS ONE FOR YOUR TRAINING/SAMPLING**
