### ISSUE TITLE
Comments on repo

### ISSUE THREAD

**Issue by joseph-hellerstein** [amitabhnag/FakeReviewGenerator#9]
I saw some pretty good unittests. That's great. But I didn't understand the use of "print" in test_utils.py.

Separately, your folder structure deviates a bit from what we're looking for. You should have a folder just under repo called FakeReviewGenerator that has your code and tests.

**Comment by amitabhnag** [comment]
Took care of these points

**Comment by lmtoan** [comment]
Completed.
